### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by zachjonesnoel** [freshworks-developers/app-placeholder-samples#2]
Add readme to this repository, briefing the purpose, structure, and navigation. Add reference docs specific to the product folder.
Add a `README.md` to the repository which should contain the details - 

- [ ]  Title
- [ ]  Description - the purpose of this repository
- [ ]  Structure with navigation to the folder
- [ ]  Details about prerequisites

**Comment by harishkotra** [comment]
Happy to take this too!

**Comment by harishkotra** [comment]
Actually done. Create PR #16
